---
- hosts: localhost
  tasks:
    - name: Create directory for registry data
      file:
        path: "/Users/lorenzomoro/registry"
        state: directory

    - name: Run Registry container
      community.docker.docker_container:
        name: registry
        image: registry:2
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
        volumes:
          - "/Users/lorenzomoro/registry:/var/lib/registry"
